### ISSUE TITLE
qt-fsarchiver 0.85-1 deb archive is dependent on a lot of -dev packages

### ISSUE THREAD

**Issue by emk2203** [DieterBaum/qt-fsarchiver#1]
the deb packages on sourceforge are dependent on a lot of -dev packages, which seem unnecessary and an artefact of the development process.

There shouldn't be a reason for a backup program to be dependent on development packages, they make the whole thing unnecessary huge.

**Comment by DieterBaum** [comment]
Thank you for the information. The program has been split into qt-fsarchiver and qt-fsarchiver-terminal, both programs have to be installed. (/usr/sbin/qt-fsarchiver and /usr/sbin/qt-fsarchiver-terminal). With the deb package this happens automatically. All installed dependencies are required.

**Comment by emk2203** [comment]
Thank you. If I install from your Ubuntu ppa, the dependencies are without the dev packages and clearly only the required ones. It was only an issue for the sourceforge package. I am closing the issue.
