### ISSUE TITLE
qt-fsarchiver-terminal fehlt im repo

### ISSUE THREAD

**Issue by Gleis1234** [DieterBaum/qt-fsarchiver#19]
Habe qt-fsarchiver aus dem repo ppa.dieterbaum/qt-fsarchiver installiert. Es fehlt aber qt-fsarchiver-terminal. Es öffnet daher nur das GUI. apt search qtfsadmin zeigt auch nicht qt-fsadmin-terminal.

**Comment by DieterBaum** [comment]
Bei https://github.com/DieterBaum/qt-fsarchiver-terminal/ findest Du das Terminal-Programm. Bei https://sourceforge.net/projects/qt-fsarchiver/ findest Du auch deb- und rpm-Pakete, die das Terminalprogramm beinhalten- Wenn Du mit Ubuntu oder Mint arbeitest findest Du hier auch fertige Pakete; https://launchpad.net/~dieterbaum
