### ISSUE TITLE
Add Qt6 support

### ISSUE THREAD

**Issue by aur-r** [DieterBaum/qt-fsarchiver#27]
With minimal changes, the program could be built with "Qt6" too.
1. Replace QRegExp with QRegularExpression.
[qt-fsarchiver-1.8.7-Use-QRegularExpression.patch.txt](https://github.com/user-attachments/files/17349160/qt-fsarchiver-1.8.7-Use-QRegularExpression.patch.txt)
2. Fix typos and types.
[qt-fsarchiver-1.8.7-Fix-typos-and-types.patch.txt](https://github.com/user-attachments/files/17349162/qt-fsarchiver-1.8.7-Fix-typos-and-types.patch.txt)
4. Add "Qt6" build option.
[qt-fsarchiver-1.8.7-Add-qt6-build-option.patch.txt](https://github.com/user-attachments/files/17349163/qt-fsarchiver-1.8.7-Add-qt6-build-option.patch.txt)

**Comment by DieterBaum** [comment]
Thanks for the tips. I will switch the project to Qt6 in a month or two

**Comment by DieterBaum** [comment]
The version with qt6 is published.
(The file README is wrong. I must change it)
